import {createServer} from 'node:http';
import {existsSync} from 'node:fs';
import {openDatabase} from './db.mjs';
import {createApp} from './app.mjs';
import {deliverRecruitment} from './integrations.mjs';
if(existsSync('.env'))process.loadEnvFile('.env');
const db=openDatabase(process.env.DATABASE_PATH),env={APP_ORIGIN:'http://localhost:3000',...process.env};
const server=createServer(createApp(db,env));server.requestTimeout=15000;server.headersTimeout=10000;
server.listen(Number(env.PORT||3000),env.HOST||'127.0.0.1',()=>console.log(`Darkness of the Fallen: ${env.APP_ORIGIN}`));
let busy=false;const timer=setInterval(async()=>{if(busy)return;busy=true;try{await deliverRecruitment(db,env);}catch{console.error('Notification delivery unavailable. Check configuration.');}finally{busy=false;}},60000);timer.unref();
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>{clearInterval(timer);server.close(()=>{db.close();process.exit(0);});});
